name = "Gantman Security"
license = "MIT"
licenselink = "https://github.com/gantmane/portfolio/blob/main/LICENSE"
description = "Custom theme for security portfolio"
homepage = "https://gantman.biz"
tags = ["portfolio", "security", "hugo"]
features = []
min_version = "0.84.0"

[author]
  name = "Evgeniy Gantman"
  homepage = "https://gantman.biz"

# If porting an existing theme
[original]
  name = "Custom"
  homepage = ""
  repo = ""
